### ISSUE TITLE
All Hands 資料作成 - 広告編

### ISSUE THREAD

**Issue by hiromichi-takeo** [supership-jp/design-overall#19]

**Comment by hiromichi-takeo** [comment]
こちらの資料を綺麗に

https://docs.google.com/a/supership.jp/presentation/d/1uIxY_Tv0G0QmoPciGXwEUtwkDgUynpyoz-Yqy_4cF_c/edit?usp=sharing

**Comment by hiromichi-takeo** [comment]
2枚目と3枚目をおねがいします！

**Comment by tmgnatto** [comment]
了解です！
