### ISSUE TITLE
Wakuba バナー

### ISSUE THREAD

**Issue by hiromichi-takeo** [supership-jp/design-overall#23]
詳細が根本さんより来る予定

**Comment by hiromichi-takeo** [comment]
[wakubaキャンペーン.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/575f95fce8960d0e001152aa/125516c66e82c728ace21e0d46ff95913680822a6d243ca067de1347aaa5dff0cbfe20c8ac0600fbfd0e39111d0014f9121c4d4eeefc802ea5b469748a540bbbd0685674c66c17acbdd01abf54a83c990dd4e8e8d51199a26867f5819d4c3f14041c80f65e3ca19e43ce58f142f300.pptx)


![lawson_smoothie_512 (2).jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/575f95fce8960d0e001152aa/125516c66e82c728ace21e0d46e4958d308d8d969ce4b04cb055f99116137621694cf16232c9a138ad4d71040c1b5ca6535d5641fffbdc2fa6be3c268b5902edd13c5974c36f14aced9003ad43eb7edf10d8eff6df0ed2e22f26e6818e4b3717061188f8543da99e49da15.jpg)

**Comment by hiromichi-takeo** [comment]
既存のものにテイスト合わせる必要はなし

**Comment by hiromichi-takeo** [comment]
7/12まで

**Comment by h-haga** [comment]
7/11に提出
