### ISSUE TITLE
FBのSupershipとScaleOutのカバー画像

### ISSUE THREAD

**Issue by h-haga** [supership-jp/design-overall#32]
### FBのSupershipカバー画像変更
- https://www.facebook.com/supership.jp/?fref=ts
- Supershipのロゴを入れつつ10コのサービスのロゴを入れた感じ

### ScaleOutカバー画像変更
- https://www.facebook.com/ScaleOutDSP/?fref=ts
- 現在の人物のカバーだといなくなってしまった人も多いためロゴを取り入れて、テック感を出したい

7/21(金)まで

**Comment by h-wakabayashi** [comment]
## Supershipカバー画像
- FBでの告知が各サービス＞コーポレートという形式が多いため、各サービスロゴを配置したい。
- vision ✕ misionのコピー等と組み合わせ
- エンブレムはアイコンで使用しているのでカバーからは削除

## ScaleOutカバー画像
- ホームページ http://www.scaleout.jp/ のイメージにロゴを配置
- ホームページリニューアル後に再度更新したい

Ciデータはここ https://drive.google.com/drive/u/0/folders/0B9uorVM7qto7MTVXTEQ2V3JKSjA

**Comment by h-wakabayashi** [comment]
@hiromichi-takeo FBカバー作成しました。どうでしょうか？（SSのキャッチコピー無くてもいいかな？とか思いましたが、どう思いますか？）
![ss_pc](https://user-images.githubusercontent.com/26217914/28446761-ea3de1d8-6e07-11e7-88a3-bdf720052bf7.jpg)
![cover_supership](https://user-images.githubusercontent.com/26217914/28446763-ecf8700a-6e07-11e7-8fc3-849c71b35237.jpg)
![scaleout_pc](https://user-images.githubusercontent.com/26217914/28446766-efbf1a6e-6e07-11e7-89c2-0b2fa3536dce.jpg)
![cover_scaleout](https://user-images.githubusercontent.com/26217914/28446767-f1f02ab2-6e07-11e7-9fbd-6507d472dcc6.jpg)

**Comment by hiromichi-takeo** [comment]
SSの方はキャッチ入れなくても良さそうですねー！

**Comment by h-wakabayashi** [comment]
![ss_pc](https://user-images.githubusercontent.com/26217914/28447602-a4e61f56-6e0c-11e7-9070-2972fc474499.jpg)
![cover_supership](https://user-images.githubusercontent.com/26217914/28447604-a7c77f08-6e0c-11e7-8120-d4b3f903a9af.jpg)
@hiromichi-takeo それではSSのカバーこちらでいきたいと思います！

**Comment by h-wakabayashi** [comment]
Scaleoutは通常赤ロゴを使用したものにしたいとリクエストがあり、来週月火に再提出

**Comment by h-wakabayashi** [comment]
![scaleout_pc a](https://user-images.githubusercontent.com/26217914/28700045-51d27284-7388-11e7-8be2-5e766a5649fc.jpg)
![scaleout_pc b](https://user-images.githubusercontent.com/26217914/28700047-5214d692-7388-11e7-9f4b-81421030d189.jpg)

**Comment by h-wakabayashi** [comment]
上記2案提出し、下記案に決定。FIXしました
![cover_scaleout](https://user-images.githubusercontent.com/26217914/28700054-5f433516-7388-11e7-9065-fdb68f0b0663.jpg)
